require("prototypes.entity.__init__")
require("prototypes.item.item-logistics")
require("prototypes.recipe.recipe-logistics")
require("prototypes.technology.technology-logistical-engineer")
require("prototypes.technology.technology-logistic-slots")
require("prototypes.technology.technology-logistic-trash-slots")
require("prototypes.technology.technology-robot-storage")

require("prototypes.item.mk3_bots")
require("prototypes.recipe.mk3_bots")
require("prototypes.technology.mk3_bots")
